const { withSentryConfig } = require("@sentry/nextjs");

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // /manifest.webmanifest used to be a static file in public/. It is now
  // generated by pages/api/manifest.js so an installed PWA's name can follow
  // the admin-set site name instead of being frozen at build time. beforeFiles
  // makes the rewrite win even if a static file at that path ever reappears
  // (e.g. a careless merge) — public/manifest.webmanifest was removed for the
  // same reason: with beforeFiles it would be dead weight, never served.
  async rewrites() {
    return {
      beforeFiles: [
        { source: "/manifest.webmanifest", destination: "/api/manifest" },
      ],
    };
  },
};

// Sentry build options are inert unless SENTRY_ORG/PROJECT/AUTH_TOKEN are set;
// runtime capture is inert unless a DSN is set (see sentry.*.config.js).
module.exports = withSentryConfig(nextConfig, {
  org: process.env.SENTRY_ORG,
  project: process.env.SENTRY_PROJECT,
  authToken: process.env.SENTRY_AUTH_TOKEN,
  silent: !process.env.CI,
  widenClientFileUpload: true,
  webpack: {
    treeshake: { removeDebugLogging: true },
  },
  telemetry: false,
});
