const { withSentryConfig } = require("@sentry/nextjs");

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // /manifest.webmanifest used to be a static file in public/. It is now
  // generated by pages/api/manifest.js so an installed PWA's name can follow
  // the admin-set site name instead of being frozen at build time. beforeFiles
  // makes the rewrite win even if a static file at that path ever reappears
  // (e.g. a careless merge) — public/manifest.webmanifest was removed for the
  // same reason: with beforeFiles it would be dead weight, never served.
  async rewrites() {
    return {
      beforeFiles: [
        { source: "/manifest.webmanifest", destination: "/api/manifest" },
      ],
    };
  },
  // Baseline response hardening. Deliberately NOT a full CSP: the pre-paint
  // theme script in pages/_document.js and Next's own bootstrap are inline, so
  // a script-src policy would need nonces threaded through both — separate
  // work. frame-ancestors is the part that closes a real hole and needs no
  // nonce.
  //
  // Referrer-Policy is strict-origin-when-cross-origin, NOT no-referrer:
  // bunny.net thumbnail hotlink protection reads the Referer, so suppressing it
  // entirely breaks every thumbnail. Sending the origin cross-origin satisfies
  // Bunny while keeping share ids, which live in the URL path, off the wire.
  //
  // No Strict-Transport-Security on purpose: Vercel sets it on its own domains,
  // and a wrong max-age/includeSubDomains is cached by browsers and cannot be
  // withdrawn quickly.
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          // /admin has one-click destructive actions; framing it anywhere is
          // clickjacking. Both headers, since X-Frame-Options is what older
          // browsers honour and frame-ancestors is what current ones do.
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Content-Security-Policy", value: "frame-ancestors 'none'" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=()",
          },
        ],
      },
    ];
  },
};

// Sentry build options are inert unless SENTRY_ORG/PROJECT/AUTH_TOKEN are set;
// runtime capture is inert unless a DSN is set (see sentry.*.config.js).
module.exports = withSentryConfig(nextConfig, {
  org: process.env.SENTRY_ORG,
  project: process.env.SENTRY_PROJECT,
  authToken: process.env.SENTRY_AUTH_TOKEN,
  silent: !process.env.CI,
  widenClientFileUpload: true,
  webpack: {
    treeshake: { removeDebugLogging: true },
  },
  telemetry: false,
});
